package com.arpadfodor.android.paw_scanner.view

import android.Manifest
import android.content.Context
import android.content.pm.PackageManager
import android.content.res.Configuration
import android.graphics.*
import android.hardware.camera2.CameraAccessException
import android.hardware.camera2.CameraCaptureSession
import android.hardware.camera2.CameraCharacteristics
import android.hardware.camera2.CameraDevice
import android.hardware.camera2.CameraManager
import android.hardware.camera2.CaptureRequest
import android.hardware.camera2.CaptureResult
import android.hardware.camera2.TotalCaptureResult
import android.media.Image
import android.media.ImageReader
import android.os.*
import android.util.Size
import android.view.LayoutInflater
import android.view.Surface
import android.view.TextureView
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import androidx.fragment.app.Fragment
import androidx.lifecycle.Observer
import androidx.lifecycle.ViewModelProviders
import com.arpadfodor.android.paw_scanner.R
import com.arpadfodor.android.paw_scanner.model.BitmapProcessor
import com.arpadfodor.android.paw_scanner.model.Recognition
import com.arpadfodor.android.paw_scanner.view.additional.AutoFitTextureView
import com.arpadfodor.android.paw_scanner.viewmodel.MainViewModel
import com.google.android.material.floatingactionbutton.FloatingActionButton
import java.util.*
import java.util.concurrent.Semaphore
import java.util.concurrent.TimeUnit
import kotlin.math.max
import kotlin.math.min

class CameraFragment: Fragment(), ImageReader.OnImageAvailableListener, View.OnClickListener {

    companion object {

        fun newInstance(): CameraFragment {
            return CameraFragment()
        }

    }

    /**
     * CameraDevice.StateCallback is called when CameraDevice changes its state
     */
    private val stateCallback = object : CameraDevice.StateCallback() {

        override fun onOpened(cd: CameraDevice) {
            //This method is called when the camera is opened; camera preview starts here
            cameraOpenCloseLock.release()
            cameraDevice = cd
            createCameraPreviewSession()
        }

        override fun onDisconnected(cd: CameraDevice) {
            cameraOpenCloseLock.release()
            cd.close()
            cameraDevice = null
        }

        override fun onError(cd: CameraDevice, error: Int) {
            cameraOpenCloseLock.release()
            cd.close()
            cameraDevice = null
            val activity = activity
            activity?.finish()
        }

    }

    /**
     * TextureView.SurfaceTextureListener handles several lifecycle events on a [ ]
     */
    private val surfaceTextureListener = object : TextureView.SurfaceTextureListener {

        override fun onSurfaceTextureAvailable(texture: SurfaceTexture, width: Int, height: Int) {
            openCamera(width, height)
        }

        override fun onSurfaceTextureSizeChanged(texture: SurfaceTexture, width: Int, height: Int) {
            configureTransform(width, height)
        }

        override fun onSurfaceTextureDestroyed(texture: SurfaceTexture): Boolean {
            return true
        }

        override fun onSurfaceTextureUpdated(texture: SurfaceTexture) {}

    }

    private val captureCallback = object : CameraCaptureSession.CaptureCallback() {
        override fun onCaptureProgressed(session: CameraCaptureSession, request: CaptureRequest, partialResult: CaptureResult) {}
        override fun onCaptureCompleted(session: CameraCaptureSession, request: CaptureRequest, result: TotalCaptureResult) {}
    }

    private lateinit var viewModel: MainViewModel

    /**
     * An ImageReader that handles preview frame capture
     */
    private var previewReader: ImageReader? = null
    /**
     * CaptureRequest.Builder] for the camera preview
     */
    private var previewRequestBuilder: CaptureRequest.Builder? = null
    /**
     * CaptureRequest generated by previewRequestBuilder
     */
    private var previewRequest: CaptureRequest? = null

    /**
     * A Semaphore to prevent the app from exiting before closing the camera
     */
    private val cameraOpenCloseLock = Semaphore(1)

    /**
     * An AutoFitTextureView for camera preview
     */
    private lateinit var textureView: AutoFitTextureView
    /**
     * A TextView to display live inference data
     */
    private lateinit var textView: TextView
    /**
     * A FloatingActionButton to switch camera
     */
    private lateinit var floatingActionButtonSwitch: FloatingActionButton

    /** A CameraCaptureSession for camera preview.  */
    private var captureSession: CameraCaptureSession? = null
    /** A reference to the opened CameraDevice  */
    private var cameraDevice: CameraDevice? = null
    /** An additional thread for running tasks that shouldn't block the UI.  */
    private var backgroundThread: HandlerThread? = null
    /** A Handler for running tasks in the background.  */
    private var backgroundHandler: Handler? = null

    private var isProcessingFrame = false
    protected var luminanceStride: Int = 0
    private var postInferenceCallback: Runnable? = null

    private var imageConverter: Runnable? = null

    private var rgbFrameBitmap: Bitmap? = null
    private var croppedBitmap: Bitmap? = null
    private var frameToCropTransform: Matrix? = null
    private var cropToFrameTransform: Matrix? = null

    private val YUVbytes = arrayOfNulls<ByteArray>(3)
    private var RGBbytes: IntArray? = null

    protected val luminance: ByteArray?
        get() = YUVbytes[0]

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        return inflater.inflate(R.layout.camera_fragment, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {

        activity?.let {
            /**
             *  create view model in activity scope
             */
            viewModel = ViewModelProviders.of(it).get(MainViewModel::class.java)
        }
        subscribeUi()

        textureView = view.findViewById<TextureView>(R.id.textureView) as AutoFitTextureView
        textView = view.findViewById(R.id.tvLiveRecognitionData)
        floatingActionButtonSwitch = view.findViewById(R.id.fabSwitch)

        floatingActionButtonSwitch.setOnClickListener {
            this.onClick(floatingActionButtonSwitch)
        }

    }

    private fun subscribeUi() {

        // Create the text observer which updates the UI in case of text change
        val recognitionObserver = Observer<List<Recognition>> { result ->
            // Update the UI, in this case, the TextView
            var resultText = ""
            for(recognition in result){
                resultText += recognition
                resultText += "\n"
            }
            textView.text = resultText
        }
        // Observe the LiveData, passing in this viewLifeCycleOwner as the LifecycleOwner and the observer
        viewModel.result.observe(viewLifecycleOwner, recognitionObserver)

    }

    fun onPreviewSizeChosen() {

        val classifierInputSize = viewModel.classifierInputSize.value!!

        rgbFrameBitmap = Bitmap.createBitmap(viewModel.previewSize.width, viewModel.previewSize.height, Bitmap.Config.ARGB_8888)
        croppedBitmap = Bitmap.createBitmap(classifierInputSize.width, classifierInputSize.height, Bitmap.Config.ARGB_8888)

        frameToCropTransform = BitmapProcessor.getTransformationMatrix(
            viewModel.previewSize.width,
            viewModel.previewSize.height,
            classifierInputSize.width,
            classifierInputSize.height,
            viewModel.sensorOrientation,
            viewModel.MAINTAIN_ASPECT
        )

        cropToFrameTransform = Matrix()
        frameToCropTransform!!.invert(cropToFrameTransform)

    }

    protected fun getRgbBytes(): IntArray? {
        imageConverter!!.run()
        return RGBbytes
    }

    /**
     * Callback for Camera2 API
     */
    override fun onImageAvailable(reader: ImageReader) {

        if (RGBbytes == null) {
            RGBbytes = IntArray(viewModel.previewSize.width * viewModel.previewSize.height)
        }

        try {
            val image = reader.acquireLatestImage() ?: return

            if (isProcessingFrame) {
                image.close()
                return
            }

            isProcessingFrame = true
            Trace.beginSection("imageAvailable")
            val planes = image.planes
            fillBytes(planes, YUVbytes)
            luminanceStride = planes[0].rowStride
            val uvRowStride = planes[1].rowStride
            val uvPixelStride = planes[1].pixelStride

            imageConverter = Runnable {
                BitmapProcessor.convertYUV420ToARGB8888(
                    YUVbytes[0]!!,
                    YUVbytes[1]!!,
                    YUVbytes[2]!!,
                    viewModel.previewSize.width,
                    viewModel.previewSize.height,
                    luminanceStride,
                    uvRowStride,
                    uvPixelStride,
                    RGBbytes!!
                )
            }

            postInferenceCallback = Runnable {
                image.close()
                isProcessingFrame = false
            }

            processImage()

        } catch (e: Exception) {
            Trace.endSection()
            return
        }

        Trace.endSection()
    }

    protected fun fillBytes(planes: Array<Image.Plane>, YUVbytes: Array<ByteArray?>) {
        // Because of the variable row stride it's not possible to know in
        // advance the actual necessary dimensions of the yuv planes.
        for (i in planes.indices) {
            val buffer = planes[i].buffer
            if (YUVbytes[i] == null) {
                YUVbytes[i] = ByteArray(buffer.capacity())
            }
            buffer.get(YUVbytes[i])
        }
    }

    @Synchronized
    override fun onStart() {
        super.onStart()
    }

    @Synchronized
    override fun onResume() {

        super.onResume()
        startBackgroundThread()

        // When the screen is turned off and turned back on, the SurfaceTexture is already available, and onSurfaceTextureAvailable will not be called
        // In that case, open a camera and start preview from here (otherwise, wait until the surface is ready in the SurfaceTextureListener)
        if (textureView.isAvailable) {
            openCamera(textureView.width, textureView.height)
        } else {
            textureView.surfaceTextureListener = surfaceTextureListener
        }

        handlerThread = HandlerThread("inference")
        handlerThread!!.start()
        handler = Handler(handlerThread!!.looper)

    }

    @Synchronized
    override fun onPause() {

        handlerThread!!.quitSafely()
        try {
            handlerThread!!.join()
            handlerThread = null
            handler = null
        } catch (e: InterruptedException) {
        }

        closeCamera()
        stopBackgroundThread()
        super.onPause()

    }

    @Synchronized
    override fun onStop() {
        super.onStop()
    }

    @Synchronized
    override fun onDestroy() {
        super.onDestroy()
    }

    @Synchronized
    fun runInBackground(r: Runnable) {
        if (handler != null) {
            handler!!.post(r)
        }
    }

    /**
     * Open the camera specified by cameraId
     */
    private fun openCamera(width: Int, height: Int){

        if(viewModel.cameraOpened){
            return
        }

        viewModel.setUpCameras()
        textureView.setAspectRatio(viewModel.textureViewSize)
        configureTransform(width, height)

        val manager = viewModel.app.getSystemService(Context.CAMERA_SERVICE) as CameraManager

        try {
            if (!cameraOpenCloseLock.tryAcquire(4000, TimeUnit.MILLISECONDS)) {
                throw RuntimeException("Time out waiting to lock camera opening")
            }
            if(viewModel.app.applicationContext.checkSelfPermission(Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED){
                manager.openCamera(viewModel.availableCameras[viewModel.currentCameraIndex.value!!]!!, stateCallback, backgroundHandler)
            }

            viewModel.cameraOpened = true

        } catch (e: CameraAccessException) {
        } catch (e: InterruptedException) {
            throw RuntimeException("Interrupted while trying to lock camera opening", e)
        }

    }

    /**
     * Closes the current CameraDevice
     */
    private fun closeCamera() {
        try {
            cameraOpenCloseLock.acquire()
            if (null != captureSession) {
                captureSession!!.close()
                captureSession = null
            }
            if (null != cameraDevice) {
                cameraDevice!!.close()
                cameraDevice = null
            }
            if (null != previewReader) {
                previewReader!!.close()
                previewReader = null
            }

            viewModel.cameraOpened = false

        } catch (e: InterruptedException) {
            throw RuntimeException("Interrupted while trying to lock camera closing", e)
        } finally {
            cameraOpenCloseLock.release()
        }
    }

    /**
     * Starts a background thread and its Handler
     */
    private fun startBackgroundThread() {
        backgroundThread = HandlerThread("ImageListener")
        backgroundThread?: return
        backgroundThread!!.start()
        backgroundHandler = Handler(backgroundThread!!.looper)
    }

    /**
     * Stops the background thread and its Handler
     */
    private fun stopBackgroundThread() {
        backgroundThread?.quitSafely()
        try {
            backgroundThread?.join()
            backgroundThread = null
            backgroundHandler = null
        } catch (e: InterruptedException) {
        }

    }

    /**
     * Creates a new CameraCaptureSession for camera preview
     */
    private fun createCameraPreviewSession() {

        onPreviewSizeChosen()

        try {

            val texture = textureView.surfaceTexture

            //Configures the size of default buffer to be the size of camera preview wanted
            texture.setDefaultBufferSize(viewModel.previewSize.width, viewModel.previewSize.height)

            //This is the output Surface we need to start preview
            val surface = Surface(texture)

            cameraDevice?: return

            //Sets up a CaptureRequest.Builder with the output Surface
            previewRequestBuilder = cameraDevice?.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW)
            previewRequestBuilder?: return
            previewRequestBuilder?.addTarget(surface)

            //Creates the reader for the preview frames
            previewReader = ImageReader.newInstance(viewModel.previewSize.width, viewModel.previewSize.height, ImageFormat.YUV_420_888, 2)
            previewReader?: return

            previewReader?.setOnImageAvailableListener(this, backgroundHandler)
            previewRequestBuilder?.addTarget(previewReader!!.surface)

            //Creates a CameraCaptureSession for camera preview
            cameraDevice!!.createCaptureSession(
                listOf(surface, previewReader!!.surface),
                object : CameraCaptureSession.StateCallback() {

                    override fun onConfigured(cameraCaptureSession: CameraCaptureSession) {
                        //The camera is already closed
                        cameraDevice?: return
                        //When the session is ready, start displaying the preview
                        captureSession = cameraCaptureSession
                        try {
                            //Auto focus should be continuous for camera preview
                            previewRequestBuilder!!.set(CaptureRequest.CONTROL_AF_MODE, CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE)
                            //Flash is automatically enabled when necessary
                            previewRequestBuilder!!.set(CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_AE_MODE_ON_AUTO_FLASH)
                            //Start displaying the camera preview
                            previewRequest = previewRequestBuilder!!.build()
                            captureSession!!.setRepeatingRequest(previewRequest!!, captureCallback, backgroundHandler)
                        } catch (e: CameraAccessException) {
                        }
                    }

                    override fun onConfigureFailed(cameraCaptureSession: CameraCaptureSession) {
                    }
                }, null
            )

        } catch (e: CameraAccessException) {
        }

    }

    /**
     * Configures the necessary Matrix transformation to the TextureView
     * Should be called after the camera preview size is determined in setUpCameraOutputs and also the size of the TextureView is fixed
     *
     * @param viewWidth The width of the TextureView
     * @param viewHeight The height of the TextureView
     */
    private fun configureTransform(viewWidth: Int, viewHeight: Int) {

        val rotation = viewModel.rotation.value
        val matrix = Matrix()
        val viewRect = RectF(0f, 0f, viewWidth.toFloat(), viewHeight.toFloat())
        val bufferRect = RectF(0f, 0f, viewModel.previewSize.height.toFloat(), viewModel.previewSize.width.toFloat())
        val centerX = viewRect.centerX()
        val centerY = viewRect.centerY()

        if (Surface.ROTATION_90 == rotation || Surface.ROTATION_270 == rotation) {
            bufferRect.offset(centerX - bufferRect.centerX(), centerY - bufferRect.centerY())
            matrix.setRectToRect(viewRect, bufferRect, Matrix.ScaleToFit.FILL)
            val scale = max(viewHeight.toFloat() / viewModel.previewSize.height, viewWidth.toFloat() / viewModel.previewSize.width)
            matrix.postScale(scale, scale, centerX, centerY)
            matrix.postRotate((90 * (rotation - 2)).toFloat(), centerX, centerY)
        } else if (Surface.ROTATION_180 == rotation) {
            matrix.postRotate(180f, centerX, centerY)
        }

        textureView.setTransform(matrix)

    }

    override fun onClick(v: View) {
        when(v.id){
            R.id.fabSwitch ->{
                viewModel.changeCamera()
            }
        }
    }

    fun processImage() {

        rgbFrameBitmap?.setPixels(getRgbBytes(), 0, viewModel.previewSize.width, 0, 0, viewModel.previewSize.width, viewModel.previewSize.height)

        val canvas = Canvas(croppedBitmap!!)
        canvas.drawBitmap(rgbFrameBitmap!!, frameToCropTransform!!, null)

        if(viewModel.isInferenceFinished.value == true){
            viewModel.recognizeLiveImage(croppedBitmap)
        }

        readyForNextImage()

    }

    protected fun readyForNextImage() {
        if (postInferenceCallback != null) {
            postInferenceCallback!!.run()
        }
    }

    private var handler: Handler? = null
    private var handlerThread: HandlerThread? = null

}
